= Technology Notes: gRPC
Florian Keintzel
1.0.1, 2022-01-04: Technology-Notes update
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== What is it?
 - a remote procedure call framework
 - functions on a server can be called remotely and therefore
 - data can not only be fetched and updated, but also
 - additional functionality can be triggered

== Similar Technologies
 - REST
 - graphQL

They both are not intended for calling functions remotely.
They are only meant to create read update and delete data. (CRUD)

== Implementation
    - add gRPC:
[source]
----
quarkus add quarkus-grpc
----
 - replace quarkus-resteasy dependency in POM with quarkus-resteasy-reactive:
[source]
----
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-resteasy-reactive</artifactId>
</dependency>
----
 - add the generate-code goal in POM (if it's not there yet):
[source]
----
<build>
    <plugins>
        <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
            <version>${quarkus-plugin.version}</version>
            <extensions>true</extensions>
            <executions>
                <execution>
                    <goals>
                        <goal>build</goal>
                        <goal>generate-code</goal>
                        <goal>generate-code-tests</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

 - create proto file
 - execute mvn compile
(to generate classes based on the proto file,
these can then be found in target/generated-sources/grpc)
 - add hello-service

== Testing
In order to test the gRPC server, the Quarkus Dev UI can be used:
http://localhost:8080/q/dev/io.quarkus.quarkus-grpc/service?name=helloworld.Greeter

