= Technology Notes: Keycloak
Florian Keintzel
1.0.1, 2022-01-31: Technology-Notes update
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== What is it?
- Authentication Module with additional features based on oAuth v2

== Similar Technologies
- oAuth v2

== Implementation

- add jax-rs and openID-Connect
[source]
----
quarkus ext add io.quarkus:quarkus-resteasy
----
[source]
----
quarkus ext add io.quarkus:quarkus-oidc
----

- add docker-compose-keycloak.yml

.docker-compose-keycloak.yml
[source,dockerfile]
----
version: '3.9'
services:
  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=passme
      - DB_VENDOR=h2
    ports:
      - '8180:8080'
    image: 'quay.io/keycloak/keycloak:15.0.2'
    networks:
      - keycloak_network

networks:
  keycloak_network:
    name: keycloak_network
    driver: bridge
----

- add keycloak-up.sh and keycloak-down.sh

.keycloak-up.sh
[source,shell script]
----
docker-compose -f docker-compose-keycloak.yml up -d
----

.keycloak-down.sh
[source,shell script]
----
docker-compose -f docker-compose-keycloak.yml down
----

Start keycloak using ``./keycloak-up.sh`` (don't forget to add execution permissions (chmod +x "filename"))

connect to localhost:8180 and login with admin credentials:
username: admin
password: passme

add client with id ``my-quarkus-service``

change access type to confidential

add new roles 'user' and 'admin'
add new user 'admin' with password 'passme'
