= Technology Notes: Validation (Hibernate Validator)
Florian Keintzel
1.0.1, 2022-01-04: Technology-Notes update
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== What is it?
 - used for validating given
    * input and output of rest services
    * parameters and return values of functions
 - can be implemented on entities


== Implementation
 - add dependency
[]
----
quarkus ext add quarkus-hibernate-validator
----

 - add preconfigured validation constraints
[]
----
@NotBlank(message = "Name cannot be blank!")
private String name;

@Min(value = 1)
private int roomNumber;

@Min(value = 1)
private int maxPeople;

@Min(value = 5)
private double pricePerNight;

@JsonbDateFormat("yyyy-MM-dd")
@NotNull(message = "Booking date cannot be null!")
private LocalDate bookingDate;
----

Endpoint validation:
[source,java]
----
@Mutation("addBooking")
@Description("Add a booking")
public Booking addBooking(@Valid Booking booking) { //<1>
    return repo.addBooking(booking);
}
----
<1> @Valid Booking throws an exception whenever one of the underlying
constraints of Booking is violated.

Repository validation:
[source,java]
----
@Transactional
public Booking addBooking(@Valid Booking booking) { //<1>
    return em.merge(booking);
}
----
<2> Same as above, the @Valid constraint throws an exception whenever
a constraint within the Booking class is breached.

== Testing
In order to test validation constraints, data must be first inserted and eventually
occurring exceptions must be caught and evaluated. (check if it's the expected exception)
